/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Me401,
  SignInBody,
  SignUpBody,
  UserDto
} from './models';

import {
  env
} from '@/config/env';

import { appInstance } from './app-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type meResponse200 = {
  data: UserDto
  status: 200
}

export type meResponse401 = {
  data: Me401
  status: 401
}

export type meResponseSuccess = (meResponse200) & {
  headers: Headers;
};
export type meResponseError = (meResponse401) & {
  headers: Headers;
};

export type meResponse = (meResponseSuccess | meResponseError)

export const getMeUrl = () => {




  return `${env.backendUrl}/auth/me`
}

/**
 * Проверяет валидность токена
 * @summary Проверка авторизации
 */
export const me = async ( options?: RequestInit): Promise<meResponse> => {

  return appInstance<meResponse>(getMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getMeMutationOptions = <TError = Me401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof me>>, TError,void, TContext>, request?: SecondParameter<typeof appInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof me>>, TError,void, TContext> => {

const mutationKey = ['me'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof me>>, void> = () => {


          return  me(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MeMutationResult = NonNullable<Awaited<ReturnType<typeof me>>>

    export type MeMutationError = Me401

    /**
 * @summary Проверка авторизации
 */
export const useMe = <TError = Me401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof me>>, TError,void, TContext>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof me>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getMeMutationOptions(options), queryClient);
    }
    export type signInResponse201 = {
  data: void
  status: 201
}

export type signInResponseSuccess = (signInResponse201) & {
  headers: Headers;
};
;

export type signInResponse = (signInResponseSuccess)

export const getSignInUrl = () => {




  return `${env.backendUrl}/auth/signIn`
}

/**
 * @summary Вход по логину и паролю
 */
export const signIn = async (signInBody: SignInBody, options?: RequestInit): Promise<signInResponse> => {

  return appInstance<signInResponse>(getSignInUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(signInBody)
  }
);}





export const getSignInQueryKey = (signInBody?: SignInBody,) => {
    return [
    'POST', `${env.backendUrl}/auth/signIn`, signInBody
    ] as const;
    }


export const getSignInQueryOptions = <TData = Awaited<ReturnType<typeof signIn>>, TError = unknown>(signInBody: SignInBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSignInQueryKey(signInBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof signIn>>> = ({ signal }) => signIn(signInBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SignInQueryResult = NonNullable<Awaited<ReturnType<typeof signIn>>>
export type SignInQueryError = unknown


export function useSignIn<TData = Awaited<ReturnType<typeof signIn>>, TError = unknown>(
 signInBody: SignInBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signIn>>,
          TError,
          Awaited<ReturnType<typeof signIn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignIn<TData = Awaited<ReturnType<typeof signIn>>, TError = unknown>(
 signInBody: SignInBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signIn>>,
          TError,
          Awaited<ReturnType<typeof signIn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignIn<TData = Awaited<ReturnType<typeof signIn>>, TError = unknown>(
 signInBody: SignInBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Вход по логину и паролю
 */

export function useSignIn<TData = Awaited<ReturnType<typeof signIn>>, TError = unknown>(
 signInBody: SignInBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signIn>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSignInQueryOptions(signInBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type signUpResponse200 = {
  data: unknown
  status: 200
}

export type signUpResponse400 = {
  data: void
  status: 400
}

export type signUpResponse500 = {
  data: void
  status: 500
}

export type signUpResponseSuccess = (signUpResponse200) & {
  headers: Headers;
};
export type signUpResponseError = (signUpResponse400 | signUpResponse500) & {
  headers: Headers;
};

export type signUpResponse = (signUpResponseSuccess | signUpResponseError)

export const getSignUpUrl = () => {




  return `${env.backendUrl}/auth/signUp`
}

/**
 * Создаёт нового пользователя и возвращает accessToken в cookie
 * @summary Регистрация нового пользователя
 */
export const signUp = async (signUpBody: SignUpBody, options?: RequestInit): Promise<signUpResponse> => {

  return appInstance<signUpResponse>(getSignUpUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(signUpBody)
  }
);}





export const getSignUpQueryKey = (signUpBody?: SignUpBody,) => {
    return [
    'POST', `${env.backendUrl}/auth/signUp`, signUpBody
    ] as const;
    }


export const getSignUpQueryOptions = <TData = Awaited<ReturnType<typeof signUp>>, TError = void>(signUpBody: SignUpBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSignUpQueryKey(signUpBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof signUp>>> = ({ signal }) => signUp(signUpBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SignUpQueryResult = NonNullable<Awaited<ReturnType<typeof signUp>>>
export type SignUpQueryError = void


export function useSignUp<TData = Awaited<ReturnType<typeof signUp>>, TError = void>(
 signUpBody: SignUpBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signUp>>,
          TError,
          Awaited<ReturnType<typeof signUp>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignUp<TData = Awaited<ReturnType<typeof signUp>>, TError = void>(
 signUpBody: SignUpBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signUp>>,
          TError,
          Awaited<ReturnType<typeof signUp>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignUp<TData = Awaited<ReturnType<typeof signUp>>, TError = void>(
 signUpBody: SignUpBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Регистрация нового пользователя
 */

export function useSignUp<TData = Awaited<ReturnType<typeof signUp>>, TError = void>(
 signUpBody: SignUpBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signUp>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSignUpQueryOptions(signUpBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






