/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { env } from "@/config/env";
import type { Me401, SignUpBody } from "./models";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type googleAuthResponse200 = {
  data: void;
  status: 200;
};

export type googleAuthResponseSuccess = googleAuthResponse200 & {
  headers: Headers;
};

export type googleAuthResponse = googleAuthResponseSuccess;

export const getGoogleAuthUrl = () => {
  return `${env.backendUrl}/auth/google`;
};

/**
 * @summary Авторизация через Google
 */
export const googleAuth = async (
  options?: RequestInit,
): Promise<googleAuthResponse> => {
  const res = await fetch(getGoogleAuthUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: googleAuthResponse["data"] = body ? JSON.parse(body) : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as googleAuthResponse;
};

export const getGoogleAuthQueryKey = () => {
  return [`${env.backendUrl}/auth/google`] as const;
};

export const getGoogleAuthQueryOptions = <
  TData = Awaited<ReturnType<typeof googleAuth>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGoogleAuthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof googleAuth>>> = ({
    signal,
  }) => googleAuth({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof googleAuth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoogleAuthQueryResult = NonNullable<
  Awaited<ReturnType<typeof googleAuth>>
>;
export type GoogleAuthQueryError = unknown;

export function useGoogleAuth<
  TData = Awaited<ReturnType<typeof googleAuth>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleAuth>>,
          TError,
          Awaited<ReturnType<typeof googleAuth>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleAuth<
  TData = Awaited<ReturnType<typeof googleAuth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleAuth>>,
          TError,
          Awaited<ReturnType<typeof googleAuth>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleAuth<
  TData = Awaited<ReturnType<typeof googleAuth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Авторизация через Google
 */

export function useGoogleAuth<
  TData = Awaited<ReturnType<typeof googleAuth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGoogleAuthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type meResponse200 = {
  data: void;
  status: 200;
};

export type meResponse401 = {
  data: Me401;
  status: 401;
};

export type meResponseSuccess = meResponse200 & {
  headers: Headers;
};
export type meResponseError = meResponse401 & {
  headers: Headers;
};

export type meResponse = meResponseSuccess | meResponseError;

export const getMeUrl = () => {
  return `${env.backendUrl}/auth/me`;
};

/**
 * Проверяет валидность токена
 * @summary Проверка авторизации
 */
export const me = async (options?: RequestInit): Promise<meResponse> => {
  const res = await fetch(getMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: meResponse["data"] = body ? JSON.parse(body) : undefined;
  return { data, status: res.status, headers: res.headers } as meResponse;
};

export const getMeQueryKey = () => {
  return [`${env.backendUrl}/auth/me`] as const;
};

export const getMeQueryOptions = <
  TData = Awaited<ReturnType<typeof me>>,
  TError = Me401,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({ signal }) =>
    me({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof me>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MeQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>;
export type MeQueryError = Me401;

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Проверка авторизации
 */

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type signInResponse201 = {
  data: void;
  status: 201;
};

export type signInResponseSuccess = signInResponse201 & {
  headers: Headers;
};

export type signInResponse = signInResponseSuccess;

export const getSignInUrl = () => {
  return `${env.backendUrl}/auth/signIn`;
};

/**
 * @summary Вход по логину и паролю
 */
export const signIn = async (
  options?: RequestInit,
): Promise<signInResponse> => {
  const res = await fetch(getSignInUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: signInResponse["data"] = body ? JSON.parse(body) : undefined;
  return { data, status: res.status, headers: res.headers } as signInResponse;
};

export const getSignInMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signIn>>,
    TError,
    void,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signIn>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["signIn"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signIn>>,
    void
  > = () => {
    return signIn(fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignInMutationResult = NonNullable<
  Awaited<ReturnType<typeof signIn>>
>;

export type SignInMutationError = unknown;

/**
 * @summary Вход по логину и паролю
 */
export const useSignIn = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signIn>>,
      TError,
      void,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof signIn>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getSignInMutationOptions(options), queryClient);
};

export type signUpResponse200 = {
  data: unknown;
  status: 200;
};

export type signUpResponse400 = {
  data: void;
  status: 400;
};

export type signUpResponse500 = {
  data: void;
  status: 500;
};

export type signUpResponseSuccess = signUpResponse200 & {
  headers: Headers;
};
export type signUpResponseError = (signUpResponse400 | signUpResponse500) & {
  headers: Headers;
};

export type signUpResponse = signUpResponseSuccess | signUpResponseError;

export const getSignUpUrl = () => {
  return `${env.backendUrl}/auth/signUp`;
};

/**
 * Создаёт нового пользователя и возвращает accessToken в cookie
 * @summary Регистрация нового пользователя
 */
export const signUp = async (
  signUpBody: SignUpBody,
  options?: RequestInit,
): Promise<signUpResponse> => {
  const res = await fetch(getSignUpUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signUpBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: signUpResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as signUpResponse;
};

export const getSignUpMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signUp>>,
    TError,
    { data: SignUpBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signUp>>,
  TError,
  { data: SignUpBody },
  TContext
> => {
  const mutationKey = ["signUp"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signUp>>,
    { data: SignUpBody }
  > = (props) => {
    const { data } = props ?? {};

    return signUp(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignUpMutationResult = NonNullable<
  Awaited<ReturnType<typeof signUp>>
>;
export type SignUpMutationBody = SignUpBody;
export type SignUpMutationError = void;

/**
 * @summary Регистрация нового пользователя
 */
export const useSignUp = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signUp>>,
      TError,
      { data: SignUpBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof signUp>>,
  TError,
  { data: SignUpBody },
  TContext
> => {
  return useMutation(getSignUpMutationOptions(options), queryClient);
};
