/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { env } from "@/config/env";
import { appInstance } from "./app-instance";
import type {
  CreateProductDto,
  Me401,
  ProductDto,
  SignInBody,
  SignUpBody,
  UpdateProductDto,
  UserDto,
} from "./models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type meResponse200 = {
  data: UserDto;
  status: 200;
};

export type meResponse401 = {
  data: Me401;
  status: 401;
};

export type meResponseSuccess = meResponse200 & {
  headers: Headers;
};
export type meResponseError = meResponse401 & {
  headers: Headers;
};

export type meResponse = meResponseSuccess | meResponseError;

export const getMeUrl = () => {
  return `${env.backendUrl}/auth/me`;
};

/**
 * Проверяет валидность токена
 * @summary Проверка авторизации
 */
export const me = async (options?: RequestInit): Promise<meResponse> => {
  return appInstance<meResponse>(getMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getMeQueryKey = () => {
  return [`${env.backendUrl}/auth/me`] as const;
};

export const getMeQueryOptions = <
  TData = Awaited<ReturnType<typeof me>>,
  TError = Me401,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
  >;
  request?: SecondParameter<typeof appInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({ signal }) =>
    me({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof me>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MeQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>;
export type MeQueryError = Me401;

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Проверка авторизации
 */

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type signInResponse201 = {
  data: void;
  status: 201;
};

export type signInResponseSuccess = signInResponse201 & {
  headers: Headers;
};

export type signInResponse = signInResponseSuccess;

export const getSignInUrl = () => {
  return `${env.backendUrl}/auth/signIn`;
};

/**
 * @summary Вход по логину и паролю
 */
export const signIn = async (
  signInBody: SignInBody,
  options?: RequestInit,
): Promise<signInResponse> => {
  return appInstance<signInResponse>(getSignInUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signInBody),
  });
};

export const getSignInMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signIn>>,
    TError,
    { data: SignInBody },
    TContext
  >;
  request?: SecondParameter<typeof appInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signIn>>,
  TError,
  { data: SignInBody },
  TContext
> => {
  const mutationKey = ["signIn"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signIn>>,
    { data: SignInBody }
  > = (props) => {
    const { data } = props ?? {};

    return signIn(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignInMutationResult = NonNullable<
  Awaited<ReturnType<typeof signIn>>
>;
export type SignInMutationBody = SignInBody;
export type SignInMutationError = unknown;

/**
 * @summary Вход по логину и паролю
 */
export const useSignIn = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signIn>>,
      TError,
      { data: SignInBody },
      TContext
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof signIn>>,
  TError,
  { data: SignInBody },
  TContext
> => {
  return useMutation(getSignInMutationOptions(options), queryClient);
};

export type signUpResponse200 = {
  data: unknown;
  status: 200;
};

export type signUpResponse400 = {
  data: void;
  status: 400;
};

export type signUpResponse500 = {
  data: void;
  status: 500;
};

export type signUpResponseSuccess = signUpResponse200 & {
  headers: Headers;
};
export type signUpResponseError = (signUpResponse400 | signUpResponse500) & {
  headers: Headers;
};

export type signUpResponse = signUpResponseSuccess | signUpResponseError;

export const getSignUpUrl = () => {
  return `${env.backendUrl}/auth/signUp`;
};

/**
 * Создаёт нового пользователя и возвращает accessToken в cookie
 * @summary Регистрация нового пользователя
 */
export const signUp = async (
  signUpBody: SignUpBody,
  options?: RequestInit,
): Promise<signUpResponse> => {
  return appInstance<signUpResponse>(getSignUpUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signUpBody),
  });
};

export const getSignUpMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signUp>>,
    TError,
    { data: SignUpBody },
    TContext
  >;
  request?: SecondParameter<typeof appInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signUp>>,
  TError,
  { data: SignUpBody },
  TContext
> => {
  const mutationKey = ["signUp"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signUp>>,
    { data: SignUpBody }
  > = (props) => {
    const { data } = props ?? {};

    return signUp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignUpMutationResult = NonNullable<
  Awaited<ReturnType<typeof signUp>>
>;
export type SignUpMutationBody = SignUpBody;
export type SignUpMutationError = void;

/**
 * @summary Регистрация нового пользователя
 */
export const useSignUp = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signUp>>,
      TError,
      { data: SignUpBody },
      TContext
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof signUp>>,
  TError,
  { data: SignUpBody },
  TContext
> => {
  return useMutation(getSignUpMutationOptions(options), queryClient);
};

export type productsControllerCreateResponse201 = {
  data: void;
  status: 201;
};

export type productsControllerCreateResponseSuccess =
  productsControllerCreateResponse201 & {
    headers: Headers;
  };

export type productsControllerCreateResponse =
  productsControllerCreateResponseSuccess;

export const getProductsControllerCreateUrl = () => {
  return `${env.backendUrl}/products`;
};

export const productsControllerCreate = async (
  createProductDto: CreateProductDto,
  options?: RequestInit,
): Promise<productsControllerCreateResponse> => {
  return appInstance<productsControllerCreateResponse>(
    getProductsControllerCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createProductDto),
    },
  );
};

export const getProductsControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerCreate>>,
    TError,
    { data: CreateProductDto },
    TContext
  >;
  request?: SecondParameter<typeof appInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerCreate>>,
  TError,
  { data: CreateProductDto },
  TContext
> => {
  const mutationKey = ["productsControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerCreate>>,
    { data: CreateProductDto }
  > = (props) => {
    const { data } = props ?? {};

    return productsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerCreate>>
>;
export type ProductsControllerCreateMutationBody = CreateProductDto;
export type ProductsControllerCreateMutationError = unknown;

export const useProductsControllerCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerCreate>>,
      TError,
      { data: CreateProductDto },
      TContext
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerCreate>>,
  TError,
  { data: CreateProductDto },
  TContext
> => {
  return useMutation(
    getProductsControllerCreateMutationOptions(options),
    queryClient,
  );
};

export type getAllProductsResponse200 = {
  data: ProductDto[];
  status: 200;
};

export type getAllProductsResponse400 = {
  data: void;
  status: 400;
};

export type getAllProductsResponse500 = {
  data: void;
  status: 500;
};

export type getAllProductsResponseSuccess = getAllProductsResponse200 & {
  headers: Headers;
};
export type getAllProductsResponseError = (
  | getAllProductsResponse400
  | getAllProductsResponse500
) & {
  headers: Headers;
};

export type getAllProductsResponse =
  | getAllProductsResponseSuccess
  | getAllProductsResponseError;

export const getGetAllProductsUrl = () => {
  return `${env.backendUrl}/products/getAll`;
};

/**
 * Получение всех товаров
 * @summary Получение товаров
 */
export const getAllProducts = async (
  options?: RequestInit,
): Promise<getAllProductsResponse> => {
  return appInstance<getAllProductsResponse>(getGetAllProductsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAllProductsQueryKey = () => {
  return [`${env.backendUrl}/products/getAll`] as const;
};

export const getGetAllProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
  >;
  request?: SecondParameter<typeof appInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllProductsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProducts>>> = ({
    signal,
  }) => getAllProducts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllProducts>>
>;
export type GetAllProductsQueryError = void;

export function useGetAllProducts<
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllProducts<
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllProducts<
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение товаров
 */

export function useGetAllProducts<
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllProductsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getProductResponse200 = {
  data: ProductDto;
  status: 200;
};

export type getProductResponse400 = {
  data: void;
  status: 400;
};

export type getProductResponse500 = {
  data: void;
  status: 500;
};

export type getProductResponseSuccess = getProductResponse200 & {
  headers: Headers;
};
export type getProductResponseError = (
  | getProductResponse400
  | getProductResponse500
) & {
  headers: Headers;
};

export type getProductResponse =
  | getProductResponseSuccess
  | getProductResponseError;

export const getGetProductUrl = (id: string) => {
  return `${env.backendUrl}/products/${id}`;
};

/**
 * Получение товара
 * @summary Получение товара
 */
export const getProduct = async (
  id: string,
  options?: RequestInit,
): Promise<getProductResponse> => {
  return appInstance<getProductResponse>(getGetProductUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetProductQueryKey = (id: string) => {
  return [`${env.backendUrl}/products/${id}`] as const;
};

export const getGetProductQueryOptions = <
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    >;
    request?: SecondParameter<typeof appInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProduct>>> = ({
    signal,
  }) => getProduct(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProduct>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProductQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProduct>>
>;
export type GetProductQueryError = void;

export function useGetProduct<
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduct>>,
          TError,
          Awaited<ReturnType<typeof getProduct>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProduct<
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduct>>,
          TError,
          Awaited<ReturnType<typeof getProduct>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProduct<
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение товара
 */

export function useGetProduct<
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProductQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type productsControllerUpdateResponse200 = {
  data: void;
  status: 200;
};

export type productsControllerUpdateResponseSuccess =
  productsControllerUpdateResponse200 & {
    headers: Headers;
  };

export type productsControllerUpdateResponse =
  productsControllerUpdateResponseSuccess;

export const getProductsControllerUpdateUrl = (id: string) => {
  return `${env.backendUrl}/products/${id}`;
};

export const productsControllerUpdate = async (
  id: string,
  updateProductDto: UpdateProductDto,
  options?: RequestInit,
): Promise<productsControllerUpdateResponse> => {
  return appInstance<productsControllerUpdateResponse>(
    getProductsControllerUpdateUrl(id),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateProductDto),
    },
  );
};

export const getProductsControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerUpdate>>,
    TError,
    { id: string; data: UpdateProductDto },
    TContext
  >;
  request?: SecondParameter<typeof appInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerUpdate>>,
  TError,
  { id: string; data: UpdateProductDto },
  TContext
> => {
  const mutationKey = ["productsControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerUpdate>>,
    { id: string; data: UpdateProductDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return productsControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerUpdate>>
>;
export type ProductsControllerUpdateMutationBody = UpdateProductDto;
export type ProductsControllerUpdateMutationError = unknown;

export const useProductsControllerUpdate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerUpdate>>,
      TError,
      { id: string; data: UpdateProductDto },
      TContext
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerUpdate>>,
  TError,
  { id: string; data: UpdateProductDto },
  TContext
> => {
  return useMutation(
    getProductsControllerUpdateMutationOptions(options),
    queryClient,
  );
};

export type productsControllerRemoveResponse200 = {
  data: void;
  status: 200;
};

export type productsControllerRemoveResponseSuccess =
  productsControllerRemoveResponse200 & {
    headers: Headers;
  };

export type productsControllerRemoveResponse =
  productsControllerRemoveResponseSuccess;

export const getProductsControllerRemoveUrl = (id: string) => {
  return `${env.backendUrl}/products/${id}`;
};

export const productsControllerRemove = async (
  id: string,
  options?: RequestInit,
): Promise<productsControllerRemoveResponse> => {
  return appInstance<productsControllerRemoveResponse>(
    getProductsControllerRemoveUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getProductsControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof productsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof appInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof productsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["productsControllerRemove"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof productsControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return productsControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProductsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerRemove>>
>;

export type ProductsControllerRemoveMutationError = unknown;

export const useProductsControllerRemove = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof productsControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof appInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof productsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getProductsControllerRemoveMutationOptions(options),
    queryClient,
  );
};
