/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Me401,
  SignInBody,
  SignUpBody
} from './models';

import {
  env
} from '@/config/env';

import { appInstance } from './app-instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const staticControllerGetIndex = (

 signal?: AbortSignal
) => {


      return appInstance<void>(
      {url: `${env.backendUrl}/`, method: 'GET', signal
    },
      );
    }




export const getStaticControllerGetIndexQueryKey = () => {
    return [
    `${env.backendUrl}/`
    ] as const;
    }


export const getStaticControllerGetIndexQueryOptions = <TData = Awaited<ReturnType<typeof staticControllerGetIndex>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetIndex>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStaticControllerGetIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof staticControllerGetIndex>>> = ({ signal }) => staticControllerGetIndex(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StaticControllerGetIndexQueryResult = NonNullable<Awaited<ReturnType<typeof staticControllerGetIndex>>>
export type StaticControllerGetIndexQueryError = unknown


export function useStaticControllerGetIndex<TData = Awaited<ReturnType<typeof staticControllerGetIndex>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticControllerGetIndex>>,
          TError,
          Awaited<ReturnType<typeof staticControllerGetIndex>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStaticControllerGetIndex<TData = Awaited<ReturnType<typeof staticControllerGetIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticControllerGetIndex>>,
          TError,
          Awaited<ReturnType<typeof staticControllerGetIndex>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStaticControllerGetIndex<TData = Awaited<ReturnType<typeof staticControllerGetIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetIndex>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStaticControllerGetIndex<TData = Awaited<ReturnType<typeof staticControllerGetIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetIndex>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStaticControllerGetIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const staticControllerGetPrivacy = (

 signal?: AbortSignal
) => {


      return appInstance<void>(
      {url: `${env.backendUrl}/privacy.html`, method: 'GET', signal
    },
      );
    }




export const getStaticControllerGetPrivacyQueryKey = () => {
    return [
    `${env.backendUrl}/privacy.html`
    ] as const;
    }


export const getStaticControllerGetPrivacyQueryOptions = <TData = Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStaticControllerGetPrivacyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof staticControllerGetPrivacy>>> = ({ signal }) => staticControllerGetPrivacy(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StaticControllerGetPrivacyQueryResult = NonNullable<Awaited<ReturnType<typeof staticControllerGetPrivacy>>>
export type StaticControllerGetPrivacyQueryError = unknown


export function useStaticControllerGetPrivacy<TData = Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticControllerGetPrivacy>>,
          TError,
          Awaited<ReturnType<typeof staticControllerGetPrivacy>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStaticControllerGetPrivacy<TData = Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticControllerGetPrivacy>>,
          TError,
          Awaited<ReturnType<typeof staticControllerGetPrivacy>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStaticControllerGetPrivacy<TData = Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStaticControllerGetPrivacy<TData = Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetPrivacy>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStaticControllerGetPrivacyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const staticControllerGetGoogle = (

 signal?: AbortSignal
) => {


      return appInstance<void>(
      {url: `${env.backendUrl}/googleef2a64e45f228d95.html`, method: 'GET', signal
    },
      );
    }




export const getStaticControllerGetGoogleQueryKey = () => {
    return [
    `${env.backendUrl}/googleef2a64e45f228d95.html`
    ] as const;
    }


export const getStaticControllerGetGoogleQueryOptions = <TData = Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStaticControllerGetGoogleQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof staticControllerGetGoogle>>> = ({ signal }) => staticControllerGetGoogle(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StaticControllerGetGoogleQueryResult = NonNullable<Awaited<ReturnType<typeof staticControllerGetGoogle>>>
export type StaticControllerGetGoogleQueryError = unknown


export function useStaticControllerGetGoogle<TData = Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticControllerGetGoogle>>,
          TError,
          Awaited<ReturnType<typeof staticControllerGetGoogle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStaticControllerGetGoogle<TData = Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticControllerGetGoogle>>,
          TError,
          Awaited<ReturnType<typeof staticControllerGetGoogle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStaticControllerGetGoogle<TData = Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStaticControllerGetGoogle<TData = Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staticControllerGetGoogle>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStaticControllerGetGoogleQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Авторизация через Google
 */
export const googleAuth = (

 signal?: AbortSignal
) => {


      return appInstance<void>(
      {url: `${env.backendUrl}/auth/google`, method: 'GET', signal
    },
      );
    }




export const getGoogleAuthQueryKey = () => {
    return [
    `${env.backendUrl}/auth/google`
    ] as const;
    }


export const getGoogleAuthQueryOptions = <TData = Awaited<ReturnType<typeof googleAuth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGoogleAuthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleAuth>>> = ({ signal }) => googleAuth(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GoogleAuthQueryResult = NonNullable<Awaited<ReturnType<typeof googleAuth>>>
export type GoogleAuthQueryError = unknown


export function useGoogleAuth<TData = Awaited<ReturnType<typeof googleAuth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleAuth>>,
          TError,
          Awaited<ReturnType<typeof googleAuth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleAuth<TData = Awaited<ReturnType<typeof googleAuth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleAuth>>,
          TError,
          Awaited<ReturnType<typeof googleAuth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleAuth<TData = Awaited<ReturnType<typeof googleAuth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Авторизация через Google
 */

export function useGoogleAuth<TData = Awaited<ReturnType<typeof googleAuth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleAuth>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGoogleAuthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Проверяет валидность токена
 * @summary Проверка авторизации
 */
export const me = (

 signal?: AbortSignal
) => {


      return appInstance<void>(
      {url: `${env.backendUrl}/auth/me`, method: 'GET', signal
    },
      );
    }




export const getMeQueryKey = () => {
    return [
    `${env.backendUrl}/auth/me`
    ] as const;
    }


export const getMeQueryOptions = <TData = Awaited<ReturnType<typeof me>>, TError = Me401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({ signal }) => me(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>
export type MeQueryError = Me401


export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof me>>,
          TError,
          Awaited<ReturnType<typeof me>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Проверка авторизации
 */

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = Me401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Вход по логину и паролю
 */
export const signIn = (
    signInBody: SignInBody,
 signal?: AbortSignal
) => {


      return appInstance<void>(
      {url: `${env.backendUrl}/auth/signIn`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signInBody, signal
    },
      );
    }




export const getSignInMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: SignInBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: SignInBody}, TContext> => {

const mutationKey = ['signIn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signIn>>, {data: SignInBody}> = (props) => {
          const {data} = props ?? {};

          return  signIn(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SignInMutationResult = NonNullable<Awaited<ReturnType<typeof signIn>>>
    export type SignInMutationBody = SignInBody
    export type SignInMutationError = unknown

    /**
 * @summary Вход по логину и паролю
 */
export const useSignIn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: SignInBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signIn>>,
        TError,
        {data: SignInBody},
        TContext
      > => {
      return useMutation(getSignInMutationOptions(options), queryClient);
    }

/**
 * Создаёт нового пользователя и возвращает accessToken в cookie
 * @summary Регистрация нового пользователя
 */
export const signUp = (
    signUpBody: SignUpBody,
 signal?: AbortSignal
) => {


      return appInstance<unknown>(
      {url: `${env.backendUrl}/auth/signUp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signUpBody, signal
    },
      );
    }




export const getSignUpMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: SignUpBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: SignUpBody}, TContext> => {

const mutationKey = ['signUp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signUp>>, {data: SignUpBody}> = (props) => {
          const {data} = props ?? {};

          return  signUp(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SignUpMutationResult = NonNullable<Awaited<ReturnType<typeof signUp>>>
    export type SignUpMutationBody = SignUpBody
    export type SignUpMutationError = void

    /**
 * @summary Регистрация нового пользователя
 */
export const useSignUp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: SignUpBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signUp>>,
        TError,
        {data: SignUpBody},
        TContext
      > => {
      return useMutation(getSignUpMutationOptions(options), queryClient);
    }

