/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProductDto,
  ProductDto,
  ProductsResponseDto,
  UpdateProductDto
} from './models';

import {
  env
} from '@/config/env';

import { appInstance } from './app-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type productsControllerCreateResponse201 = {
  data: void
  status: 201
}

export type productsControllerCreateResponseSuccess = (productsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type productsControllerCreateResponse = (productsControllerCreateResponseSuccess)

export const getProductsControllerCreateUrl = () => {




  return `${env.backendUrl}/products`
}

export const productsControllerCreate = async (createProductDto: CreateProductDto, options?: RequestInit): Promise<productsControllerCreateResponse> => {

  return appInstance<productsControllerCreateResponse>(getProductsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProductDto)
  }
);}





export const getProductsControllerCreateQueryKey = (createProductDto?: CreateProductDto,) => {
    return [
    'POST', `${env.backendUrl}/products`, createProductDto
    ] as const;
    }


export const getProductsControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof productsControllerCreate>>, TError = unknown>(createProductDto: CreateProductDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsControllerCreateQueryKey(createProductDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsControllerCreate>>> = ({ signal }) => productsControllerCreate(createProductDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof productsControllerCreate>>>
export type ProductsControllerCreateQueryError = unknown


export function useProductsControllerCreate<TData = Awaited<ReturnType<typeof productsControllerCreate>>, TError = unknown>(
 createProductDto: CreateProductDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof productsControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsControllerCreate<TData = Awaited<ReturnType<typeof productsControllerCreate>>, TError = unknown>(
 createProductDto: CreateProductDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof productsControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsControllerCreate<TData = Awaited<ReturnType<typeof productsControllerCreate>>, TError = unknown>(
 createProductDto: CreateProductDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsControllerCreate<TData = Awaited<ReturnType<typeof productsControllerCreate>>, TError = unknown>(
 createProductDto: CreateProductDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsControllerCreateQueryOptions(createProductDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getAllProductsResponse200 = {
  data: ProductsResponseDto
  status: 200
}

export type getAllProductsResponse400 = {
  data: void
  status: 400
}

export type getAllProductsResponse500 = {
  data: void
  status: 500
}

export type getAllProductsResponseSuccess = (getAllProductsResponse200) & {
  headers: Headers;
};
export type getAllProductsResponseError = (getAllProductsResponse400 | getAllProductsResponse500) & {
  headers: Headers;
};

export type getAllProductsResponse = (getAllProductsResponseSuccess | getAllProductsResponseError)

export const getGetAllProductsUrl = () => {




  return `${env.backendUrl}/products/getAll`
}

/**
 * Получение всех товаров
 * @summary Получение товаров
 */
export const getAllProducts = async ( options?: RequestInit): Promise<getAllProductsResponse> => {

  return appInstance<getAllProductsResponse>(getGetAllProductsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllProductsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAllProducts>>, TError,void, TContext>, request?: SecondParameter<typeof appInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getAllProducts>>, TError,void, TContext> => {

const mutationKey = ['getAllProducts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getAllProducts>>, void> = () => {


          return  getAllProducts(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetAllProductsMutationResult = NonNullable<Awaited<ReturnType<typeof getAllProducts>>>

    export type GetAllProductsMutationError = void

    /**
 * @summary Получение товаров
 */
export const useGetAllProducts = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAllProducts>>, TError,void, TContext>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getAllProducts>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetAllProductsMutationOptions(options), queryClient);
    }
    export type getProductResponse200 = {
  data: ProductDto
  status: 200
}

export type getProductResponse400 = {
  data: void
  status: 400
}

export type getProductResponse500 = {
  data: void
  status: 500
}

export type getProductResponseSuccess = (getProductResponse200) & {
  headers: Headers;
};
export type getProductResponseError = (getProductResponse400 | getProductResponse500) & {
  headers: Headers;
};

export type getProductResponse = (getProductResponseSuccess | getProductResponseError)

export const getGetProductUrl = (id: string,) => {




  return `${env.backendUrl}/products/${id}`
}

/**
 * Получение товара
 * @summary Получение товара
 */
export const getProduct = async (id: string, options?: RequestInit): Promise<getProductResponse> => {

  return appInstance<getProductResponse>(getGetProductUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProductMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getProduct>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof appInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getProduct>>, TError,{id: string}, TContext> => {

const mutationKey = ['getProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getProduct>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  getProduct(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetProductMutationResult = NonNullable<Awaited<ReturnType<typeof getProduct>>>

    export type GetProductMutationError = void

    /**
 * @summary Получение товара
 */
export const useGetProduct = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getProduct>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getProduct>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getGetProductMutationOptions(options), queryClient);
    }
    export type productsControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type productsControllerUpdateResponseSuccess = (productsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type productsControllerUpdateResponse = (productsControllerUpdateResponseSuccess)

export const getProductsControllerUpdateUrl = (id: string,) => {




  return `${env.backendUrl}/products/${id}`
}

export const productsControllerUpdate = async (id: string,
    updateProductDto: UpdateProductDto, options?: RequestInit): Promise<productsControllerUpdateResponse> => {

  return appInstance<productsControllerUpdateResponse>(getProductsControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProductDto)
  }
);}





export const getProductsControllerUpdateQueryKey = (id: string,
    updateProductDto?: UpdateProductDto,) => {
    return [
    'PATCH', `${env.backendUrl}/products/${id}`, updateProductDto
    ] as const;
    }


export const getProductsControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof productsControllerUpdate>>, TError = unknown>(id: string,
    updateProductDto: UpdateProductDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsControllerUpdateQueryKey(id,updateProductDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsControllerUpdate>>> = ({ signal }) => productsControllerUpdate(id,updateProductDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof productsControllerUpdate>>>
export type ProductsControllerUpdateQueryError = unknown


export function useProductsControllerUpdate<TData = Awaited<ReturnType<typeof productsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProductDto: UpdateProductDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof productsControllerUpdate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsControllerUpdate<TData = Awaited<ReturnType<typeof productsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProductDto: UpdateProductDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof productsControllerUpdate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsControllerUpdate<TData = Awaited<ReturnType<typeof productsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProductDto: UpdateProductDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsControllerUpdate<TData = Awaited<ReturnType<typeof productsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProductDto: UpdateProductDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsControllerUpdateQueryOptions(id,updateProductDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type productsControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type productsControllerRemoveResponseSuccess = (productsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type productsControllerRemoveResponse = (productsControllerRemoveResponseSuccess)

export const getProductsControllerRemoveUrl = (id: string,) => {




  return `${env.backendUrl}/products/${id}`
}

export const productsControllerRemove = async (id: string, options?: RequestInit): Promise<productsControllerRemoveResponse> => {

  return appInstance<productsControllerRemoveResponse>(getProductsControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getProductsControllerRemoveQueryKey = (id: string,) => {
    return [
    'DELETE', `${env.backendUrl}/products/${id}`
    ] as const;
    }


export const getProductsControllerRemoveQueryOptions = <TData = Awaited<ReturnType<typeof productsControllerRemove>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsControllerRemoveQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsControllerRemove>>> = ({ signal }) => productsControllerRemove(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsControllerRemoveQueryResult = NonNullable<Awaited<ReturnType<typeof productsControllerRemove>>>
export type ProductsControllerRemoveQueryError = unknown


export function useProductsControllerRemove<TData = Awaited<ReturnType<typeof productsControllerRemove>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerRemove>>,
          TError,
          Awaited<ReturnType<typeof productsControllerRemove>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsControllerRemove<TData = Awaited<ReturnType<typeof productsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsControllerRemove>>,
          TError,
          Awaited<ReturnType<typeof productsControllerRemove>>
        > , 'initialData'
      >, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsControllerRemove<TData = Awaited<ReturnType<typeof productsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsControllerRemove<TData = Awaited<ReturnType<typeof productsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof appInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsControllerRemoveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






