/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseDtoDataItem } from './paginatedResponseDtoDataItem';

export interface PaginatedResponseDto {
  data: PaginatedResponseDtoDataItem[];
  total: number;
  page: number;
  limit: number;
}
