/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';

export interface ProductsResponseDto {
  data: ProductDto[];
  total: number;
  page: number;
  limit: number;
}
