/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */

export interface ProductDto {
  /** ID товара */
  id: number;
  /** Имя товара */
  name: string;
  /** Описание товара */
  description?: string;
  /** Цена */
  price: string;
  /** Фото товара */
  image?: string;
}
