/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Todo example
 * The Todo API description
 * OpenAPI spec version: 1.0
 */

export interface UserDto {
  /** ID пользователя */
  id: number;
  /** Email пользователя */
  email: string;
  /** Имя пользователя */
  firstName?: string;
  /** Имя пользователя */
  picture?: string;
  /** Фамилия пользователя */
  lastName?: string;
  /** Фамилия пользователя */
  createdAt?: string;
  /** Фамилия пользователя */
  updatedAt?: string;
}
